In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import os

In [2]:
input_dir = '../data/20240620/'
output_dir = '../data/20240620/'

In [3]:
# remove problematic data points (since they were repeated on a later time)
os.makedirs(output_dir, exist_ok=True)

# Define the list of gene prefixes
cols = ['agaI', 'eptA', 'fimI', 'ghoS', 'yaeL', 'yeeD', 'yfdQ', 'yfgJ']

# Iterate through the files in the input directory
for p in os.listdir(input_dir):
    if p.startswith('clones_batch1'):
        d1_od = pd.read_excel(os.path.join(input_dir, p), sheet_name='OD600', index_col=0)
        d1_od = d1_od.drop(columns=[col for col in d1_od.columns if any(col.startswith(gene) for gene in cols)])
        
        d1_gfp = pd.read_excel(os.path.join(input_dir, p), sheet_name='gfp', index_col=0)
        d1_gfp = d1_gfp.drop(columns=[col for col in d1_gfp.columns if any(col.startswith(gene) for gene in cols)])
        
        output_file = os.path.join(output_dir, 'modified_' + p)
        with pd.ExcelWriter(output_file) as writer:
            d1_od.to_excel(writer, sheet_name='OD600')
            d1_gfp.to_excel(writer, sheet_name='gfp')
    
    elif p.startswith('clones_batch2'):
        d2_od = pd.read_excel(os.path.join(input_dir, p), sheet_name='OD600', index_col=0)
        d2_od = d2_od.drop(columns=[col for col in d2_od.columns if any(col.startswith(gene) for gene in cols)])
        
        d2_gfp = pd.read_excel(os.path.join(input_dir, p), sheet_name='gfp', index_col=0)
        d2_gfp = d2_gfp.drop(columns=[col for col in d2_gfp.columns if any(col.startswith(gene) for gene in cols)])
        
        output_file = os.path.join(output_dir, 'modified_' + p)
        with pd.ExcelWriter(output_file) as writer:
            d2_od.to_excel(writer, sheet_name='OD600')
            d2_gfp.to_excel(writer, sheet_name='gfp')

In [4]:
!ls ../data/20240620/ | grep modified

modified_clones_batch1_R1_10.06.24.xlsx
modified_clones_batch1_R2_11.06.24.xlsx
modified_clones_batch1_R3_12.06.24.xlsx
modified_clones_batch2_R1_16.06.24.xlsx
modified_clones_batch2_R2_17.06.24.xlsx
modified_clones_batch2_R3_18.06.24.xlsx
modified_clones_batch3_R1_20.06.24.xlsx
modified_clones_batch3_R2_21.06.24.xlsx
modified_clones_batch3_R3_22.06.24.xlsx

In [5]:
# List of filenames (prefixes) for each day's data
filenames = ['modified_clones_batch1_R1_10.06.24.xlsx',
             'modified_clones_batch1_R2_11.06.24.xlsx',
             'modified_clones_batch1_R3_12.06.24.xlsx']

# Initialize empty lists to store averaged data for each day
od_averages = []
gfp_averages = []

# Loop through each filename
for day_index, filename in enumerate(filenames, start =1):
    # Read OD600 and GFP data from Excel file
    df_od = pd.read_excel(os.path.join(input_dir, filename), sheet_name='OD600', index_col=0)
    df_gfp = pd.read_excel(os.path.join(input_dir, filename), sheet_name='gfp', index_col=0)
    
    # Average out od and gfp of replicates
    df_od.columns = [f"{col.split('_')[0]}_{day_index}" for col in df_od.columns]
    df_od_avg = df_od.groupby(df_od.columns, axis=1).mean()

    # Average out fluorescence of replicates
    df_gfp.columns = [f"{col.split('_')[0]}_{day_index}" for col in df_gfp.columns]
    df_gfp_avg = df_gfp.groupby(df_gfp.columns, axis=1).mean()
    
    # Append averaged data to lists
    od_averages.append(df_od_avg)
    gfp_averages.append(df_gfp_avg)

# Concatenate all days' averaged data into single DataFrames
df_od_combined = pd.concat(od_averages, axis=1)
df_gfp_combined = pd.concat(gfp_averages, axis=1)

# Reorder columns to ensure cadB from each day appears next to each other
df_od_combined = df_od_combined.reindex(sorted(df_od_combined.columns), axis=1)
df_gfp_combined = df_gfp_combined.reindex(sorted(df_gfp_combined.columns), axis=1)


# Create Excel writer object
output_file = os.path.join(output_dir, 'averaged_data_clones1.xlsx')  # Adjust output file path as needed
with pd.ExcelWriter(output_file) as writer:
    # Write OD600 data to 'OD600' sheet
    df_od_combined.to_excel(writer, sheet_name='OD600')

    # Write GFP data to 'gfp' sheet
    df_gfp_combined.to_excel(writer, sheet_name='gfp')

print(f"Data saved to {output_file}")

Data saved to ../data/20240620/averaged_data_clones1.xlsx

/tmp/ipykernel_456/3045707509.py:18: FutureWarning: DataFrame.groupby with axis=1 is deprecated. Do `frame.T.groupby(...)` without axis instead.
  df_od_avg = df_od.groupby(df_od.columns, axis=1).mean()
/tmp/ipykernel_456/3045707509.py:22: FutureWarning: DataFrame.groupby with axis=1 is deprecated. Do `frame.T.groupby(...)` without axis instead.
  df_gfp_avg = df_gfp.groupby(df_gfp.columns, axis=1).mean()
/tmp/ipykernel_456/3045707509.py:18: FutureWarning: DataFrame.groupby with axis=1 is deprecated. Do `frame.T.groupby(...)` without axis instead.
  df_od_avg = df_od.groupby(df_od.columns, axis=1).mean()
/tmp/ipykernel_456/3045707509.py:22: FutureWarning: DataFrame.groupby with axis=1 is deprecated. Do `frame.T.groupby(...)` without axis instead.
  df_gfp_avg = df_gfp.groupby(df_gfp.columns, axis=1).mean()
/tmp/ipykernel_456/3045707509.py:18: FutureWarning: DataFrame.groupby with axis=1 is deprecated. Do `frame.T.groupby(...)` without axis instead.
  df_od_avg = df_od.groupby(df_od.columns, axis=1).mean()
/tmp/ipykernel_456/3045707509.py:22: FutureWarning: DataFrame.groupby with axis=1 is deprecated. Do `frame.T.groupby(...)` without axis instead.
  df_gfp_avg = df_gfp.groupby(df_gfp.columns, axis=1).mean()

In [6]:
# List of filenames (prefixes) for each day's data
filenames = ['modified_clones_batch2_R1_16.06.24.xlsx',
             'modified_clones_batch2_R2_17.06.24.xlsx',
             'modified_clones_batch2_R3_18.06.24.xlsx']

# Initialize empty lists to store averaged data for each day
od_averages = []
gfp_averages = []

# Loop through each filename
for day_index, filename in enumerate(filenames, start =1):
    # Read OD600 and GFP data from Excel file
    df_od = pd.read_excel(os.path.join(input_dir, filename), sheet_name='OD600', index_col=0)
    df_gfp = pd.read_excel(os.path.join(input_dir, filename), sheet_name='gfp', index_col=0)
    
    # Average out od and gfp of replicates
    df_od.columns = [f"{col.split('_')[0]}_{day_index}" for col in df_od.columns]
    df_od_avg = df_od.groupby(df_od.columns, axis=1).mean()

    # Average out fluorescence of replicates
    df_gfp.columns = [f"{col.split('_')[0]}_{day_index}" for col in df_gfp.columns]
    df_gfp_avg = df_gfp.groupby(df_gfp.columns, axis=1).mean()
    
    # Append averaged data to lists
    od_averages.append(df_od_avg)
    gfp_averages.append(df_gfp_avg)

# Concatenate all days' averaged data into single DataFrames
df_od_combined = pd.concat(od_averages, axis=1)
df_gfp_combined = pd.concat(gfp_averages, axis=1)

# Reorder columns to ensure cadB from each day appears next to each other
df_od_combined = df_od_combined.reindex(sorted(df_od_combined.columns), axis=1)
df_gfp_combined = df_gfp_combined.reindex(sorted(df_gfp_combined.columns), axis=1)


# Create Excel writer object
output_file = os.path.join(output_dir, 'averaged_data_clones2.xlsx')  # Adjust output file path as needed
with pd.ExcelWriter(output_file) as writer:
    # Write OD600 data to 'OD600' sheet
    df_od_combined.to_excel(writer, sheet_name='OD600')

    # Write GFP data to 'gfp' sheet
    df_gfp_combined.to_excel(writer, sheet_name='gfp')

print(f"Data saved to {output_file}")

Data saved to ../data/20240620/averaged_data_clones2.xlsx

/tmp/ipykernel_456/3975890373.py:18: FutureWarning: DataFrame.groupby with axis=1 is deprecated. Do `frame.T.groupby(...)` without axis instead.
  df_od_avg = df_od.groupby(df_od.columns, axis=1).mean()
/tmp/ipykernel_456/3975890373.py:22: FutureWarning: DataFrame.groupby with axis=1 is deprecated. Do `frame.T.groupby(...)` without axis instead.
  df_gfp_avg = df_gfp.groupby(df_gfp.columns, axis=1).mean()
/tmp/ipykernel_456/3975890373.py:18: FutureWarning: DataFrame.groupby with axis=1 is deprecated. Do `frame.T.groupby(...)` without axis instead.
  df_od_avg = df_od.groupby(df_od.columns, axis=1).mean()
/tmp/ipykernel_456/3975890373.py:22: FutureWarning: DataFrame.groupby with axis=1 is deprecated. Do `frame.T.groupby(...)` without axis instead.
  df_gfp_avg = df_gfp.groupby(df_gfp.columns, axis=1).mean()
/tmp/ipykernel_456/3975890373.py:18: FutureWarning: DataFrame.groupby with axis=1 is deprecated. Do `frame.T.groupby(...)` without axis instead.
  df_od_avg = df_od.groupby(df_od.columns, axis=1).mean()
/tmp/ipykernel_456/3975890373.py:22: FutureWarning: DataFrame.groupby with axis=1 is deprecated. Do `frame.T.groupby(...)` without axis instead.
  df_gfp_avg = df_gfp.groupby(df_gfp.columns, axis=1).mean()

In [7]:
# List of filenames (prefixes) for each day's data
filenames = ['clones_batch3_R1_20.06.24.xlsx', 'clones_batch3_R2_21.06.24.xlsx', 'clones_batch3_R3_22.06.24.xlsx']

# Initialize empty lists to store averaged data for each day
od_averages = []
gfp_averages = []

# Loop through each filename
for day_index, filename in enumerate(filenames, start =1):
    # Read OD600 and GFP data from Excel file
    df_od = pd.read_excel(os.path.join(input_dir, filename), sheet_name='OD600', index_col=0)
    df_gfp = pd.read_excel(os.path.join(input_dir, filename), sheet_name='gfp', index_col=0)
    
    # Average out od and gfp of replicates
    df_od.columns = [f"{col.split('_')[0]}_{day_index}" for col in df_od.columns]
    df_od_avg = df_od.groupby(df_od.columns, axis=1).mean()

    # Average out fluorescence of replicates
    df_gfp.columns = [f"{col.split('_')[0]}_{day_index}" for col in df_gfp.columns]
    df_gfp_avg = df_gfp.groupby(df_gfp.columns, axis=1).mean()
    
    # Append averaged data to lists
    od_averages.append(df_od_avg)
    gfp_averages.append(df_gfp_avg)

# Concatenate all days' averaged data into single DataFrames
df_od_combined = pd.concat(od_averages, axis=1)
df_gfp_combined = pd.concat(gfp_averages, axis=1)

# Reorder columns to ensure cadB from each day appears next to each other
df_od_combined = df_od_combined.reindex(sorted(df_od_combined.columns), axis=1)
df_gfp_combined = df_gfp_combined.reindex(sorted(df_gfp_combined.columns), axis=1)


# Create Excel writer object
output_file = os.path.join(output_dir, 'averaged_data_clones3.xlsx')  # Adjust output file path as needed
with pd.ExcelWriter(output_file) as writer:
    # Write OD600 data to 'OD600' sheet
    df_od_combined.to_excel(writer, sheet_name='OD600')

    # Write GFP data to 'gfp' sheet
    df_gfp_combined.to_excel(writer, sheet_name='gfp')

print(f"Data saved to {output_file}")

/tmp/ipykernel_456/918979028.py:16: FutureWarning: DataFrame.groupby with axis=1 is deprecated. Do `frame.T.groupby(...)` without axis instead.
  df_od_avg = df_od.groupby(df_od.columns, axis=1).mean()
/tmp/ipykernel_456/918979028.py:20: FutureWarning: DataFrame.groupby with axis=1 is deprecated. Do `frame.T.groupby(...)` without axis instead.
  df_gfp_avg = df_gfp.groupby(df_gfp.columns, axis=1).mean()
/tmp/ipykernel_456/918979028.py:16: FutureWarning: DataFrame.groupby with axis=1 is deprecated. Do `frame.T.groupby(...)` without axis instead.
  df_od_avg = df_od.groupby(df_od.columns, axis=1).mean()
/tmp/ipykernel_456/918979028.py:20: FutureWarning: DataFrame.groupby with axis=1 is deprecated. Do `frame.T.groupby(...)` without axis instead.
  df_gfp_avg = df_gfp.groupby(df_gfp.columns, axis=1).mean()
/tmp/ipykernel_456/918979028.py:16: FutureWarning: DataFrame.groupby with axis=1 is deprecated. Do `frame.T.groupby(...)` without axis instead.
  df_od_avg = df_od.groupby(df_od.columns, axis=1).mean()
/tmp/ipykernel_456/918979028.py:20: FutureWarning: DataFrame.groupby with axis=1 is deprecated. Do `frame.T.groupby(...)` without axis instead.
  df_gfp_avg = df_gfp.groupby(df_gfp.columns, axis=1).mean()

Data saved to ../data/20240620/averaged_data_clones3.xlsx

In [8]:
df_gfp_combined

,Blank_1,Blank_2,Blank_3,DH5a_1,DH5a_2,DH5a_3,agaI-ctrl_1,agaI-ctrl_2,agaI-ctrl_3,agaI-test_1,...,yfgJ-ctrl_3,yfgJ-test_1,yfgJ-test_2,yfgJ-test_3,yqiD-ctrl_1,yqiD-ctrl_2,yqiD-ctrl_3,yqiD-test_1,yqiD-test_2,yqiD-test_3
Time,,,,,,,,,,,,,,,,,,,,,
30,624.333333,629.666667,641.333333,1161.000000,1178.666667,1187.000000,633.000000,643.666667,648.000000,633.000000,...,637.666667,625.333333,618.666667,633.000000,624.666667,620.000000,637.333333,647.666667,640.000000,646.333333
60,603.666667,619.000000,639.000000,1157.000000,1158.333333,1163.666667,625.000000,630.333333,626.000000,627.666667,...,635.000000,624.000000,625.000000,631.000000,614.333333,625.666667,629.666667,639.000000,625.333333,650.333333
90,608.666667,608.666667,621.333333,1133.333333,1137.666667,1166.333333,605.000000,620.666667,632.000000,613.666667,...,637.000000,613.000000,623.666667,631.000000,616.333333,615.333333,627.333333,643.333333,626.666667,637.333333
120,605.333333,611.000000,615.333333,1148.000000,1136.666667,1167.333333,611.666667,626.333333,630.333333,619.333333,...,632.333333,613.000000,621.666667,630.000000,609.666667,615.666667,626.000000,651.333333,627.000000,653.333333
150,607.333333,627.333333,627.666667,1136.333333,1152.333333,1161.666667,612.666667,626.333333,639.666667,620.666667,...,639.000000,612.666667,616.666667,624.666667,618.000000,622.000000,629.333333,646.000000,645.000000,655.333333
180,613.666667,618.666667,622.333333,1132.000000,1126.000000,1163.000000,623.666667,633.000000,625.666667,625.000000,...,625.666667,617.333333,619.666667,642.666667,612.666667,617.000000,629.333333,673.000000,653.333333,669.000000
210,607.666667,627.333333,628.000000,1128.666667,1141.000000,1153.666667,617.000000,630.666667,649.000000,618.333333,...,641.000000,615.333333,626.000000,635.666667,618.333333,617.333333,629.000000,691.333333,655.333333,674.000000
240,609.000000,619.333333,630.333333,1138.333333,1150.666667,1173.666667,623.000000,631.666667,636.000000,631.333333,...,638.000000,625.333333,621.666667,631.333333,622.333333,615.333333,636.666667,717.000000,670.333333,698.333333
270,608.333333,622.333333,623.666667,1141.333333,1150.666667,1171.666667,637.666667,641.000000,656.666667,625.666667,...,649.000000,622.333333,635.666667,646.666667,629.666667,633.333333,626.333333,741.000000,680.666667,704.333333
300,608.666667,624.333333,640.666667,1136.000000,1152.333333,1170.333333,632.666667,644.000000,641.666667,638.000000,...,642.000000,633.333333,629.666667,640.666667,630.000000,632.333333,653.333333,793.000000,714.666667,744.000000
330,620.666667,649.666667,635.666667,1148.000000,1154.666667,1186.333333,638.333333,639.333333,650.000000,630.000000,...,660.666667,642.666667,636.666667,645.666667,638.666667,633.666667,655.333333,845.000000,726.000000,760.666667
360,615.000000,635.666667,646.000000,1144.666667,1155.666667,1178.000000,640.666667,645.333333,662.666667,636.333333,...,665.666667,639.000000,639.333333,655.000000,636.333333,637.666667,654.666667,898.666667,766.666667,809.000000
390,623.666667,642.666667,644.000000,1157.333333,1154.000000,1169.333333,648.000000,663.000000,675.000000,643.666667,...,670.666667,636.000000,655.666667,666.000000,640.666667,641.333333,664.666667,960.666667,789.666667,853.000000
420,620.000000,646.666667,642.333333,1157.333333,1173.666667,1171.000000,653.333333,679.000000,674.333333,654.666667,...,667.000000,654.000000,673.000000,675.666667,654.666667,651.000000,651.666667,1038.666667,837.333333,908.333333
450,638.000000,634.666667,646.666667,1176.000000,1177.000000,1176.666667,660.000000,671.333333,678.666667,664.000000,...,678.333333,668.666667,669.666667,680.333333,651.000000,659.000000,674.333333,1152.333333,885.000000,974.333333
480,625.333333,648.000000,658.666667,1153.000000,1173.333333,1191.666667,668.000000,688.666667,700.333333,658.666667,...,695.000000,668.666667,678.666667,708.666667,656.000000,669.666667,671.000000,1279.000000,961.333333,1028.000000
510,631.333333,640.000000,648.333333,1177.000000,1178.000000,1189.333333,674.666667,680.333333,695.333333,673.000000,...,692.666667,684.666667,690.666667,702.000000,683.000000,682.333333,691.333333,1447.666667,1019.666667,1111.666667
540,637.333333,658.666667,662.333333,1184.000000,1181.333333,1191.666667,686.333333,694.666667,692.333333,675.666667,...,698.333333,695.000000,706.666667,712.000000,682.000000,675.666667,698.666667,1644.333333,1103.666667,1231.666667
570,631.000000,654.333333,656.666667,1173.000000,1194.666667,1194.000000,691.333333,712.333333,726.666667,689.333333,...,720.000000,710.333333,719.333333,719.333333,697.666667,696.333333,703.333333,1888.000000,1209.666667,1369.333333
600,643.000000,658.666667,661.666667,1178.333333,1201.333333,1198.000000,707.333333,724.000000,733.666667,703.666667,...,737.333333,722.333333,737.666667,734.000000,708.666667,722.666667,721.000000,2133.666667,1356.333333,1561.000000
630,651.000000,657.333333,668.666667,1191.333333,1205.333333,1201.000000,731.333333,735.333333,743.000000,711.333333,...,744.000000,744.666667,751.666667,759.000000,721.666667,731.000000,739.000000,2371.666667,1554.333333,1781.000000
660,643.000000,660.666667,665.666667,1187.000000,1216.333333,1184.333333,738.000000,757.000000,764.000000,733.666667,...,763.000000,775.000000,782.000000,760.000000,744.666667,717.000000,753.666667,2586.333333,1775.000000,1991.333333
690,655.000000,676.000000,670.333333,1213.666667,1212.666667,1209.000000,757.333333,758.000000,778.333333,753.333333,...,789.333333,796.333333,790.000000,798.666667,758.333333,762.666667,758.666667,2823.666667,2047.666667,2269.000000
720,660.666667,678.000000,678.666667,1207.333333,1216.666667,1224.666667,785.666667,790.000000,809.000000,753.333333,...,822.000000,823.000000,821.000000,830.000000,769.000000,772.000000,787.333333,3057.333333,2366.000000,2481.000000
750,661.333333,677.333333,693.666667,1230.666667,1250.000000,1261.333333,814.666667,806.333333,829.333333,795.000000,...,858.333333,871.000000,864.666667,857.000000,801.000000,792.333333,806.666667,3410.666667,2607.333333,2717.333333
780,666.333333,679.000000,681.000000,1276.666667,1296.333333,1291.000000,837.666667,847.333333,873.666667,836.333333,...,908.666667,936.000000,934.000000,910.666667,829.333333,812.666667,836.333333,3876.333333,2859.333333,2931.000000
810,663.333333,676.666667,687.333333,1342.666667,1349.000000,1338.666667,912.333333,879.000000,905.000000,873.666667,...,940.666667,982.666667,978.333333,968.333333,858.333333,862.000000,859.666667,4391.666667,3125.333333,3215.333333
840,657.000000,689.666667,707.333333,1401.333333,1416.666667,1414.666667,971.000000,924.333333,965.666667,956.333333,...,1022.000000,1070.333333,1050.666667,1042.666667,927.000000,903.666667,933.666667,5038.333333,3437.333333,3560.333333
870,664.333333,691.666667,703.333333,1480.333333,1508.666667,1512.666667,1036.666667,985.333333,1027.666667,1020.333333,...,1103.000000,1171.000000,1163.000000,1121.333333,990.000000,971.333333,989.000000,5757.333333,3833.000000,4046.333333
900,670.333333,679.000000,701.000000,1575.333333,1586.666667,1596.333333,1130.333333,1058.666667,1109.333333,1126.000000,...,1175.000000,1275.333333,1248.000000,1206.333333,1073.333333,1019.333333,1048.000000,6730.666667,4350.000000,4594.333333
930,679.333333,701.666667,697.333333,1651.333333,1714.333333,1694.666667,1234.666667,1163.333333,1213.000000,1204.000000,...,1276.333333,1390.666667,1370.333333,1318.666667,1173.000000,1117.000000,1110.333333,7735.000000,4907.333333,5209.000000
960,686.666667,707.666667,697.333333,1766.666667,1821.666667,1811.333333,1348.000000,1257.666667,1300.666667,1320.333333,...,1360.666667,1479.000000,1494.000000,1392.000000,1273.333333,1213.333333,1213.666667,8666.333333,5583.666667,5985.333333
990,688.000000,697.333333,710.333333,1925.000000,1973.333333,1960.666667,1456.666667,1375.666667,1418.333333,1411.333333,...,1472.666667,1568.000000,1574.333333,1472.666667,1373.666667,1328.333333,1314.333333,9564.000000,6397.666667,6920.333333

Normalise data and save into a single dataframe

In [9]:
gfp_data = None

files = ['averaged_data_clones1.xlsx', 'averaged_data_clones2.xlsx', 'averaged_data_clones3.xlsx']
columns_to_exclude = ['Blank', 'DH5a', 'pOT2', 'msfGFP', 'ydeQ-ctrl', 'ydeQ-test']

for file in files:
    od_df = pd.read_excel(os.path.join(input_dir, file), sheet_name = 'OD600', index_col = 0)
    gfp_df = pd.read_excel(os.path.join(input_dir, file), sheet_name = 'gfp', index_col = 0)
    
    # Average out od of replicates
    od_df.columns = [col.split('_')[0] for col in od_df.columns]
    od_averaged = od_df.groupby(od_df.columns, axis=1).mean()

    # Average out fluorescence of replicates
    gfp_df.columns = [col.split('_')[0] for col in gfp_df.columns]
    fluorescence_averaged = gfp_df.groupby(gfp_df.columns, axis=1).mean()

    # Normalize OD600 by the blank 
    normalized_od_blank = od_averaged.sub(od_averaged['Blank'], axis=0)

    # Normalize fluorescence by the blank and OD600
    normalized_flo_blank = fluorescence_averaged.sub(fluorescence_averaged['Blank'], axis=0)
    fluorescence_od = normalized_flo_blank / normalized_od_blank
    
    norm_gfp = fluorescence_od.drop(columns = [col for col in columns_to_exclude if col in fluorescence_od.columns])
                                    
    
    if gfp_data is None:
        gfp_data = norm_gfp
    else:
        gfp_data = pd.merge(gfp_data, norm_gfp, left_index = True, right_index = True, how = 'outer')
        
gfp_data.reindex(sorted(gfp_data.columns), axis=1)

/tmp/ipykernel_456/1702645090.py:12: FutureWarning: DataFrame.groupby with axis=1 is deprecated. Do `frame.T.groupby(...)` without axis instead.
  od_averaged = od_df.groupby(od_df.columns, axis=1).mean()
/tmp/ipykernel_456/1702645090.py:16: FutureWarning: DataFrame.groupby with axis=1 is deprecated. Do `frame.T.groupby(...)` without axis instead.
  fluorescence_averaged = gfp_df.groupby(gfp_df.columns, axis=1).mean()
/tmp/ipykernel_456/1702645090.py:12: FutureWarning: DataFrame.groupby with axis=1 is deprecated. Do `frame.T.groupby(...)` without axis instead.
  od_averaged = od_df.groupby(od_df.columns, axis=1).mean()
/tmp/ipykernel_456/1702645090.py:16: FutureWarning: DataFrame.groupby with axis=1 is deprecated. Do `frame.T.groupby(...)` without axis instead.
  fluorescence_averaged = gfp_df.groupby(gfp_df.columns, axis=1).mean()

/tmp/ipykernel_456/1702645090.py:12: FutureWarning: DataFrame.groupby with axis=1 is deprecated. Do `frame.T.groupby(...)` without axis instead.
  od_averaged = od_df.groupby(od_df.columns, axis=1).mean()
/tmp/ipykernel_456/1702645090.py:16: FutureWarning: DataFrame.groupby with axis=1 is deprecated. Do `frame.T.groupby(...)` without axis instead.
  fluorescence_averaged = gfp_df.groupby(gfp_df.columns, axis=1).mean()

,agaI-ctrl,agaI-test,cadB-ctrl,cadB-test,eptA-ctrl,eptA-test,fimI-ctrl,fimI-test,ghoS-ctrl,ghoS-test,...,yfdQ-ctrl,yfdQ-test,yfgJ-ctrl,yfgJ-test,yhaV-ctrl,yhaV-test,yodB-ctrl,yodB-test,yqiD-ctrl,yqiD-test
Time,,,,,,,,,,,,,,,,,,,,,
30,5500.000000,2681.818182,3263.888889,53703.703704,1789.473684,4714.285714,2888.888889,814.814815,5384.615385,-62.500000,...,1360.000000,7071.428571,76.923077,-2619.047619,631.578947,1642.857143,1625.000000,10560.000000,-2500.000000,5800.000000
60,3470.588235,3708.333333,3263.333333,46387.096774,1454.545455,3880.000000,3096.774194,758.620690,6571.428571,1750.000000,...,2038.461538,4800.000000,2062.500000,2619.047619,2515.151515,6312.500000,3080.000000,10500.000000,1263.157895,6913.043478
90,3352.941176,3200.000000,3511.428571,51090.909091,2136.363636,6966.666667,2677.419355,4285.714286,10714.285714,3611.111111,...,3708.333333,3529.411765,7461.538462,3954.545455,1348.837209,6411.764706,785.714286,8857.142857,3050.000000,8956.521739
120,4782.608696,3733.333333,3713.888889,47780.487805,1640.000000,4142.857143,5305.555556,2676.470588,9000.000000,2043.478261,...,4545.454545,9238.095238,4650.000000,3807.692308,3312.500000,2083.333333,1419.354839,10513.513514,2034.482759,9677.419355
150,2333.333333,2000.000000,4413.698630,45346.938776,41.666667,3277.777778,333.333333,264.705882,3666.666667,-1142.857143,...,580.645161,5263.157895,3550.000000,-892.857143,1709.090909,3250.000000,2228.571429,13785.714286,807.692308,7636.363636
180,3192.307692,3090.909091,5226.912929,42566.666667,222.222222,3475.000000,2275.000000,512.820513,3400.000000,391.304348,...,2486.486486,5480.000000,-416.666667,2272.727273,1466.666667,1413.793103,2842.105263,13444.444444,448.275862,10820.512821
210,4208.333333,1111.111111,5763.496144,42681.159420,1740.740741,3780.487805,2948.717949,2175.000000,4880.000000,772.727273,...,2026.315789,4583.333333,2640.000000,1200.000000,892.307692,64.516129,953.488372,17354.166667,151.515152,10282.608696
240,3310.344828,3805.555556,6959.899749,39139.534884,2777.777778,4111.111111,3022.727273,2456.521739,6481.481481,3318.181818,...,2095.238095,5571.428571,2545.454545,1372.093023,2438.356164,8294.117647,4227.272727,23192.307692,1382.352941,12611.111111
270,7593.750000,4595.238095,7529.832936,38905.660377,3516.129032,5180.000000,4521.739130,3730.769231,6060.606061,4230.769231,...,4142.857143,6257.142857,3805.555556,3212.765957,734.939759,5875.000000,3566.037736,23034.482759,2625.000000,12936.507937
300,3350.000000,3795.918367,8911.564626,39193.798450,3205.882353,3836.363636,3230.769231,2288.135593,4400.000000,3259.259259,...,3392.857143,3975.000000,2478.260870,1578.947368,2157.894737,4895.833333,3107.142857,26317.460317,2680.851064,14921.052632
330,1413.043478,1140.350877,10597.402597,41178.807947,1225.000000,2215.384615,1406.779661,1414.285714,1958.333333,1058.823529,...,1343.283582,2306.122449,1763.636364,826.086957,2587.155963,7321.428571,5354.838710,28800.000000,1226.415094,13880.434783
360,2943.396226,2206.349206,13132.653061,42597.883598,2023.809524,3583.333333,2444.444444,2086.419753,4036.363636,3205.128205,...,2428.571429,3982.456140,2477.611940,1341.463415,2380.952381,7507.462687,4445.945946,27448.717949,1573.770492,16196.261682
390,3661.290323,1873.239437,15653.703704,43436.734694,2437.500000,3192.771084,2712.328767,1606.382979,4630.769231,2325.581395,...,2797.752809,3590.909091,2512.500000,1479.166667,2013.698630,6670.886076,3682.352941,27465.909091,1557.142857,16500.000000
420,3959.459459,2841.463415,19285.945073,45041.916168,3481.481481,3372.340426,2400.000000,2212.962963,3526.315789,2058.823529,...,3186.274510,3844.155844,2670.103093,2531.531532,1957.317073,6681.318681,4600.000000,26742.268041,1790.123457,17276.315789
450,3162.790698,2708.333333,23112.033195,44819.354839,2442.622951,3099.099099,2615.384615,2283.464567,4033.333333,3721.311475,...,3380.165289,3923.913043,2210.526316,2223.880597,2243.523316,6648.648649,4715.596330,25219.298246,2010.309278,18205.555556
480,3640.776699,2196.581197,26069.575472,44669.367909,3597.222222,3338.461538,2299.065421,2476.821192,3557.522124,3270.270270,...,3212.328767,3071.428571,2166.666667,2296.296296,2043.478261,6860.465116,5164.062500,24969.230769,1672.413793,18140.271493
510,3161.290323,2918.518519,28071.500504,43626.444159,3768.292683,3390.728477,3057.851240,2241.758242,4437.956204,3383.720930,...,3655.172414,3107.142857,2150.537634,2307.317073,1802.158273,7098.684211,4917.241379,25869.863014,3000.000000,18301.470588
540,2331.081081,1826.086957,29245.315162,42127.771911,2216.494845,2675.977654,2602.836879,2061.403509,3579.881657,2669.902913,...,2925.925926,2775.862069,1563.265306,1778.625954,1752.136752,7153.439153,5209.302326,26267.857143,1719.298246,17730.994152
570,3156.424581,2517.766497,30794.520548,40398.745520,3272.727273,3246.511628,3053.571429,1819.112628,3951.219512,3269.841270,...,3247.272727,2510.917031,1877.300613,1826.470588,1396.436526,7426.778243,5372.641509,27313.432836,2177.570093,17992.874109
600,2700.892857,2080.000000,31916.551724,38606.156275,3044.776119,2739.622642,2408.866995,1650.130548,3507.751938,2584.415584,...,2745.901639,2043.046358,1562.642369,1562.076749,1194.207836,7118.971061,5060.714286,28704.000000,2046.931408,17711.281071
630,2415.224913,1953.560372,32616.550853,37015.635622,2295.597484,2388.724036,2236.947791,1407.258065,3291.793313,2678.947368,...,2372.188139,1673.267327,1226.804124,1454.703833,902.887139,6673.123487,4798.387097,29968.944099,1735.849057,17321.981424
660,2305.039788,1757.142857,32318.915802,35737.410072,2726.804124,2185.354691,2226.006192,1484.800000,3102.803738,3084.033613,...,2350.710900,1674.812030,1247.011952,1440.607735,824.120603,6545.454545,4374.245473,31794.749403,1515.400411,16772.959184
690,1804.526749,1537.753223,31576.538664,34948.923385,2298.387097,1855.595668,1826.506024,1284.987277,2541.133455,2537.704918,...,2114.956737,1228.323699,1093.071355,1269.018743,733.952049,6374.651811,4094.955490,33553.380783,1302.652106,16194.327731
720,1809.523810,1270.430906,30853.602570,35300.373909,2056.074766,1764.790765,1690.566038,1276.260504,2593.342981,2361.809045,...,2016.865079,1160.958904,1071.726439,1212.389381,565.429093,5949.222798,3853.496115,34774.018945,1146.191646,15643.046944
750,1667.553191,1359.281437,31569.494225,35179.120486,1651.658768,1641.025641,1491.704374,1315.151515,2541.423571,2119.460501,...,1943.200000,1034.766697,1044.037940,1203.292770,612.626263,5656.739812,3585.749793,35369.519833,1048.479087,15096.846847
780,1756.875688,1419.291339,31722.654927,34325.630252,1581.005587,1743.217054,1587.871287,1418.521177,2508.212560,2098.335855,...,1922.663080,1146.788991,1122.646891,1359.159159,602.000870,5406.268837,3297.383535,35422.131148,1053.613054,14664.747281
810,1817.934783,1473.214286,31647.129546,34345.158709,1634.218289,1772.364217,1621.181263,1491.784038,2504.830918,2170.909091,...,1962.039660,1082.692308,1154.860772,1380.612245,646.693460,5100.192678,3084.745763,34869.814933,1066.237942,14556.856187
840,1805.369128,1562.165775,32029.144385,35405.648892,1439.285714,1792.780749,1574.241181,1532.619279,2540.300546,2072.620216,...,1999.015263,1119.500272,1250.957040,1458.169076,618.509469,4948.465775,2951.934827,34541.433655,1142.015005,14501.694915
870,1845.341615,1662.731872,33028.613353,35935.715891,1483.870968,1933.256617,1647.612643,1673.666527,2656.268393,2203.674121,...,2118.181818,1220.394737,1410.482020,1613.872832,674.504624,4844.091360,2886.824905,33541.615416,1223.901099,14310.671611
900,1984.101749,1789.794007,33200.702679,36674.825913,1620.273532,2125.062783,1719.241192,1838.880484,2854.855372,2394.300861,...,2288.379324,1333.471589,1531.718963,1760.307477,733.100233,4864.741207,2836.668629,32948.885077,1308.400000,14671.213209
930,2070.238631,1897.488678,33867.426515,36821.720514,1574.426230,2288.392857,1822.416974,1874.267101,2951.487414,2504.751258,...,2364.540466,1407.352941,1662.492364,1873.322933,777.029870,4816.290282,2770.218228,32131.176471,1429.189189,14704.474829
960,2194.276501,1915.236427,33659.323965,36590.154867,1653.742596,2354.346124,1953.271028,1834.467120,3111.201629,2673.031026,...,2205.767077,1559.733777,1623.594036,1840.755735,799.098761,4721.213463,2738.847792,31828.916902,1576.608951,14683.301861
990,2242.455775,1858.600583,33677.721702,36359.738247,1746.357013,2333.222259,1940.273038,1801.477833,3081.033881,2903.624733,...,2010.737948,1645.771733,1541.556145,1757.674419,814.814815,4667.259435,2685.338726,31042.983853,1680.863477,14791.034156

In [10]:
gfp_data.to_csv(os.path.join(output_dir, 'normalised_gfp_all_clones.tsv'), sep = '\t')

Negative control set: the same chain applied to the genes where no change in expression is expected

In [11]:
notarget_dir = '../data/20260731/'

cap_min = 16 * 60
read_interval = 30

days = ['20260729', '20260730']

In [12]:
plate_map = pd.read_csv(os.path.join(notarget_dir, 'plate_map.tsv'), sep = '\t', dtype = str).fillna('')
well_names = {f"{row['row']}{int(row['column'])}": row['name'] for _, row in plate_map.iterrows() if row['name']}

def read_plate(path):
    df = pd.read_csv(path, sep = '\t')
    df = df.drop(columns = [col for col in df.columns if col.startswith('T°')])
    df = df.set_index('Time')

    # Index by elapsed minutes, like the batch tables above
    df.index = [(i + 1) * read_interval for i in range(len(df))]
    df.index.name = 'Time'

    # 'OVRFLW' marks a saturated detector, it is not a number
    df = df.apply(pd.to_numeric, errors = 'coerce')

    df = df[[col for col in df.columns if col in well_names]]
    return df[df.index <= cap_min]

In [13]:
od_averages = []
gfp_averages = []

for day_index, day in enumerate(days, start = 1):
    # Read OD600 and GFP data from the plate reader export
    df_od = read_plate(os.path.join(notarget_dir, day, 'od.tsv'))
    df_gfp = read_plate(os.path.join(notarget_dir, day, 'gfp.tsv'))

    # Average out od of replicates
    df_od.columns = [f"{well_names[col]}_{day_index}" for col in df_od.columns]
    df_od_avg = df_od.groupby(df_od.columns, axis=1).mean()

    # Average out fluorescence of replicates
    df_gfp.columns = [f"{well_names[col]}_{day_index}" for col in df_gfp.columns]
    df_gfp_avg = df_gfp.groupby(df_gfp.columns, axis=1).mean()

    # Append averaged data to lists
    od_averages.append(df_od_avg)
    gfp_averages.append(df_gfp_avg)

df_od_combined = pd.concat(od_averages, axis=1)
df_gfp_combined = pd.concat(gfp_averages, axis=1)

df_od_combined = df_od_combined.reindex(sorted(df_od_combined.columns), axis=1)
df_gfp_combined = df_gfp_combined.reindex(sorted(df_gfp_combined.columns), axis=1)

output_file = os.path.join(notarget_dir, 'averaged_data_notarget.xlsx')
with pd.ExcelWriter(output_file) as writer:
    df_od_combined.to_excel(writer, sheet_name='OD600')

    df_gfp_combined.to_excel(writer, sheet_name='gfp')

/tmp/ipykernel_456/440730409.py:13: FutureWarning: DataFrame.groupby with axis=1 is deprecated. Do `frame.T.groupby(...)` without axis instead.
  df_od_avg = df_od.groupby(df_od.columns, axis=1).mean()
/tmp/ipykernel_456/440730409.py:17: FutureWarning: DataFrame.groupby with axis=1 is deprecated. Do `frame.T.groupby(...)` without axis instead.
  df_gfp_avg = df_gfp.groupby(df_gfp.columns, axis=1).mean()
/tmp/ipykernel_456/440730409.py:13: FutureWarning: DataFrame.groupby with axis=1 is deprecated. Do `frame.T.groupby(...)` without axis instead.
  df_od_avg = df_od.groupby(df_od.columns, axis=1).mean()
/tmp/ipykernel_456/440730409.py:17: FutureWarning: DataFrame.groupby with axis=1 is deprecated. Do `frame.T.groupby(...)` without axis instead.
  df_gfp_avg = df_gfp.groupby(df_gfp.columns, axis=1).mean()

Data saved to ../data/20260731/averaged_data_notarget.xlsx

In [14]:
gfp_data_notarget = None

files = ['averaged_data_notarget.xlsx']
columns_to_exclude = ['Blank', 'pOT2']

for file in files:
    od_df = pd.read_excel(os.path.join(notarget_dir, file), sheet_name = 'OD600', index_col = 0)
    gfp_df = pd.read_excel(os.path.join(notarget_dir, file), sheet_name = 'gfp', index_col = 0)

    # Average out od of replicates
    od_df.columns = [col.split('_')[0] for col in od_df.columns]
    od_averaged = od_df.groupby(od_df.columns, axis=1).mean()

    # Average out fluorescence of replicates
    gfp_df.columns = [col.split('_')[0] for col in gfp_df.columns]
    fluorescence_averaged = gfp_df.groupby(gfp_df.columns, axis=1).mean()

    # Normalize OD600 by the blank 
    normalized_od_blank = od_averaged.sub(od_averaged['Blank'], axis=0)

    # Normalize fluorescence by the blank and OD600
    normalized_flo_blank = fluorescence_averaged.sub(fluorescence_averaged['Blank'], axis=0)
    fluorescence_od = normalized_flo_blank / normalized_od_blank

    norm_gfp = fluorescence_od.drop(columns = [col for col in columns_to_exclude if col in fluorescence_od.columns])


    if gfp_data_notarget is None:
        gfp_data_notarget = norm_gfp
    else:
        gfp_data_notarget = pd.merge(gfp_data_notarget, norm_gfp, left_index = True, right_index = True, how = 'outer')

gfp_data_notarget.reindex(sorted(gfp_data_notarget.columns), axis=1)

/tmp/ipykernel_456/3808855304.py:12: FutureWarning: DataFrame.groupby with axis=1 is deprecated. Do `frame.T.groupby(...)` without axis instead.
  od_averaged = od_df.groupby(od_df.columns, axis=1).mean()
/tmp/ipykernel_456/3808855304.py:16: FutureWarning: DataFrame.groupby with axis=1 is deprecated. Do `frame.T.groupby(...)` without axis instead.
  fluorescence_averaged = gfp_df.groupby(gfp_df.columns, axis=1).mean()

,amyA-ctrl,amyA-test,dmlR-ctrl,dmlR-test,flhC-ctrl,flhC-test,fliT-ctrl,fliT-test,rclR-ctrl,rclR-test,ybaM-ctrl,ybaM-test,ycjY-ctrl,ycjY-test,ygiL-ctrl,ygiL-test
Time,,,,,,,,,,,,,,,,
30,6837.700146,5015.828678,7040.918164,4785.163776,3050.476190,4594.147583,2442.817294,4211.583924,27070.972887,67853.200883,2958.089669,3591.816367,3176.818951,4036.687631,2890.476190,2926.443203
60,6753.405995,5308.544304,6308.394161,4995.065789,2719.798658,4474.299065,2630.154639,4406.382979,25224.860335,62041.015625,3157.439446,2866.129032,3166.158537,3269.642857,2605.357143,2522.364217
90,7334.156887,5284.067797,6037.765539,4880.565371,2914.523975,3997.940268,2363.427257,4331.735379,26875.824835,59214.345288,3166.017147,3110.961668,3021.839841,3170.583776,3175.887696,2538.619275
120,6031.762837,5049.307479,5881.344759,4921.846154,2447.778419,4164.217805,2472.709064,3948.547718,29105.930056,59402.882636,2978.585334,2763.896533,2760.736196,3294.191131,2744.452398,2621.983914
150,6426.099158,5583.256244,6219.200888,4315.706806,2529.556650,3984.536082,2617.542297,4027.738265,34623.748863,64211.292200,2748.044693,2665.610860,2996.611810,3399.679829,2522.528160,2607.044831
180,6757.297081,5727.450215,6470.207852,4654.111162,2667.821568,3876.651982,2595.728737,3702.750146,41511.909410,70875.305623,3052.989791,2778.558226,3133.799918,3458.876404,3039.395575,2555.774537
210,7098.106713,5454.771526,7392.871446,4599.767532,2607.493634,3368.421053,2948.556256,3050.439611,49693.410720,77513.685046,3118.588428,2738.727979,3515.065580,3511.817125,2918.525262,2441.999371
240,7172.949640,5449.667733,8041.735674,5131.734662,2667.653152,3044.296354,3217.632381,3132.756675,56025.633723,84926.614173,3206.979131,2661.754219,3598.105949,3621.020093,2771.065795,2541.217740
270,7386.066763,5345.390898,8265.905383,5014.947683,2822.284908,2803.921569,3253.835425,2979.345955,60573.676681,90032.061069,3030.456853,2687.861272,3521.229868,3520.423601,3054.368932,2688.833124
300,7300.773694,5314.263074,8105.342525,4786.386818,2516.411787,2436.562366,3099.848427,2470.167552,60101.678749,89039.579350,3086.889573,2569.543620,3322.512486,3460.632960,2838.668043,2570.235254
330,7010.149162,5299.934683,7614.643865,4998.725100,2521.501404,2431.173741,2889.959958,2491.568974,58173.102728,85552.215415,2713.169461,2752.191548,3184.444110,3195.233035,2579.248522,2553.018842
360,6779.431832,5423.489434,7206.198608,4990.944200,2382.271800,2505.505506,2870.086688,2506.547388,56503.174033,91465.572101,2632.140615,2867.885515,3099.800399,3211.512718,2436.335183,2539.813289
390,7241.005635,5469.951083,7295.966030,5171.943712,2538.032656,2577.178030,2993.038493,2719.965050,58558.691207,97655.640373,2638.341544,2787.814382,3162.332545,3333.333333,2422.528736,2611.481481
420,7129.948518,5181.273000,7312.686436,5112.172252,2507.873390,2465.155176,3023.083265,2749.774001,56172.300082,97447.337278,2723.371516,2668.305013,3093.991484,3151.449876,2343.125111,2505.958511
450,6568.869210,4990.546892,7169.872682,4794.979350,2428.983094,2275.565050,2801.989730,2587.938657,54813.801740,90901.099612,2652.623749,2712.431382,3085.364289,3193.061942,2360.811991,2421.201945
480,6447.919639,5146.869352,7281.838348,4796.089245,2472.801276,2169.064184,2830.383560,2474.425178,55158.411039,88160.520156,2640.920111,2899.005703,3187.406629,3171.991690,2275.127427,2480.760747
510,6815.568443,5361.516643,8157.162795,5508.528785,2670.427268,2386.704556,2994.856064,2837.019848,59850.023798,91845.868196,2713.219000,3102.945020,3213.891794,3395.058635,2497.110125,2736.271996
540,6708.274715,5204.764371,8184.416553,5813.326860,2652.009283,2482.480105,2944.556094,2986.976144,57946.294307,92690.315454,2806.799851,3089.248377,3294.701576,3362.876045,2567.188127,2784.940230
570,6429.694544,5127.688055,8014.753688,5810.605296,2767.520240,2641.816276,3123.755888,3085.733957,56213.238166,90988.037678,2949.279329,3309.883243,3293.146715,3393.602582,2641.527320,2933.469639
600,6595.812993,5350.656531,8323.950683,5720.432562,2945.756052,2632.491262,3258.866509,2946.044743,56126.534777,86866.301088,3062.932891,3643.267330,3444.268902,3543.979561,2792.450254,3066.065455
630,6953.798450,5713.338679,8666.417119,5870.198119,3151.804866,2774.345577,3490.451232,2909.623888,55143.918631,86053.003334,3334.959045,3753.233831,3614.689874,3733.967905,2970.685668,3256.414377
660,7051.201405,5434.681006,8556.438746,6057.095563,3312.694964,3241.563851,3616.704743,3460.019718,52371.758328,85055.785352,3467.616286,3320.343493,3771.535274,3864.798181,3098.603099,3155.314979
690,6973.717850,4988.415183,8458.533313,5899.821035,3385.165192,2868.727195,3743.532671,3132.145509,49491.132881,84375.551997,3581.330067,3272.608598,3882.512449,3972.519467,3238.513271,2735.470632
720,6848.358484,4976.413967,8220.176918,5756.776227,3235.965045,2400.977102,3756.174165,2698.992867,46838.456231,84186.657456,3580.221697,3230.501588,3923.031634,3958.855666,3265.676378,2444.309343
750,7029.761773,5121.411066,8220.439097,5803.934596,3534.080459,2175.008048,3923.216406,2460.247770,45607.012465,88363.484708,3886.729533,3297.390744,4097.200841,4162.500814,3534.252976,2344.667602
780,6938.355751,5248.120617,8150.461447,5897.328089,3468.548435,2108.847922,3850.418970,2397.779794,43818.562415,93692.798881,3804.269594,3406.639004,4070.380353,4111.593417,3500.646592,2189.091379
810,6951.688242,5545.013989,8106.129624,6037.770619,3524.861140,2024.315491,3827.543024,2334.336155,43043.113453,88502.384529,3883.381754,3466.457598,4132.307104,4146.579680,3556.000552,2095.252795
840,6955.178225,5914.108611,8044.696887,6469.573817,3439.284013,1965.068618,3786.273649,2321.219519,42203.069157,94974.063600,3813.383583,3403.311485,4070.922374,4006.659408,3536.731154,2054.561253
870,7013.937028,6357.817626,8112.997003,6932.161130,3476.286944,1948.184333,3847.806332,2339.558360,41630.349337,NaN,3864.011854,3428.491740,4213.985298,4075.875977,3602.070177,2004.690874
900,6841.272592,6761.610244,7838.418804,7388.750266,3428.957645,1958.376450,3706.751530,2370.991993,41770.335686,NaN,3670.169581,3324.521499,3988.223158,3818.776739,3410.661680,2009.582734
930,6829.807692,7082.170396,7770.463576,7901.939655,3293.961468,1967.521692,3661.306807,2429.747739,41917.602480,NaN,3587.623220,3364.758885,3910.891089,3821.189392,3288.403614,2022.940119
960,6812.219871,7528.816317,7760.475878,8350.537890,3207.550587,2003.194220,3529.559769,2468.188627,42360.478160,NaN,3503.540337,3457.903762,3804.811074,3759.125743,3148.256243,2074.900315

In [15]:
gfp_data_notarget.to_csv(os.path.join(notarget_dir, 'normalised_gfp_notarget.tsv'), sep = '\t')